services:

  db:
    image: postgres:15
    container_name: e_bank_db
    environment:
      POSTGRES_DB: e_bank
      POSTGRES_USER: fiestta
      POSTGRES_PASSWORD: fiestta
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    restart: unless-stopped

  greenplum:
    image: andruche/greenplum:6.25.3-4seg-slim-amd64
    container_name: e_bank_greenplum
    ports:
      - "5433:5432"
      - "8081:8081"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=e_bank_dwh
    volumes:
      - ./etl:/shared_data
    restart: unless-stopped

  greenplum_init:
    image: postgres:15-alpine
    container_name: greenplum_initializer
    depends_on:
      - greenplum
    environment:
      - PGPASSWORD=gpadmin
    volumes:
      - ./migrations:/scripts
    command: >
      sh -c "
      echo '/// Ожидание старта Greenplum ///' &&
      until pg_isready -h greenplum -p 5432 -U gpadmin; do
        sleep 5;
      done &&
      sleep 5;
      echo '/// Создание бд ///' &&
      psql -h greenplum -U gpadmin -d postgres -c 'CREATE DATABASE e_bank_dwh;' || true &&
      echo '/// Создание колоночных таблиц ///' &&
      psql -h greenplum -U gpadmin -d e_bank_dwh -f /scripts/init_greenplum.sql &&
      echo '/// Инициализация есть ///'
      "

  airflow_db:
    image: postgres:15
    container_name: airflow_postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - airflow_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

  metabase:
    image: metabase/metabase:latest
    container_name: e_bank_bi
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: e_bank_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_SERVER_JSON_FILE: "/pgadmin4/servers.json"
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin-servers.json:/pgadmin4/servers.json
    depends_on:
      - db
    restart: unless-stopped

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: e_bank_cloudbeaver
    ports:
      - "8088:8978"
    volumes:
      - ./cloudbeaver-data-sources.json:/opt/cloudbeaver/workspace/GlobalConfiguration/.dbeaver/data-sources.json
    restart: unless-stopped

  airflow:
    image: apache/airflow:2.8.1
    container_name: e_bank_airflow
    user: "${AIRFLOW_UID:-50000}:0"
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./etl:/opt/airflow/etl
      - ./dbt_project:/opt/airflow/dbt_project
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow_db/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=fiestta
      - _AIRFLOW_WWW_USER_PASSWORD=fiestta
      - PYTHONPATH=/opt/airflow/etl
      - _PIP_ADDITIONAL_REQUIREMENTS=faker psycopg2-binary pandas requests dbt-core==1.7.4 dbt-postgres==1.7.4
      - AIRFLOW_CONN_E_BANK_CONN=postgresql://fiestta:fiestta@db:5432/e_bank
      - AIRFLOW_CONN_GREENPLUM_DWH=postgresql://gpadmin:gpadmin@greenplum:5432/e_bank_dwh
      - AIRFLOW_VAR_RATES_API_URL=https://api.exchangerate-api.com/v4/latest/USD
    command: standalone
    depends_on:
      db:
        condition: service_healthy
      airflow_db: 
        condition: service_healthy

volumes:
  postgres_data:
  airflow_db_data: