name: 'e_bank_dbt'
version: '1.0.0'
config-version: 2

profile: 'e_bank_gp'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  e_bank_dbt:
    staging:
      +materialized: view
    marts:
      +materialized: table